version: '3'
services:
  node:
    image: node:lts
    container_name: nest-web
  db:
    image: mysql:5.7
    container_name: nest-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'
volumes:
  db_data:
